server {
    listen 80;
    server_name studio-web.jabez.cloud;

    root /home/ubuntu/websites/jabez-studio-web/public;
    index index.html;

    location / {
        try_files $uri $uri/ $uri.html /index.html;
    }

    location /en {
        try_files $uri $uri/ /en/index.html;
    }

    location /_nuxt/ {
        expires 1y;
        add_header Cache-Control "public, immutable";
    }
}